# Generated by Django 5.0 on 2024-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_remove_tarefa_data_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='colaborador',
            field=models.CharField(choices=[('ruan', 'Ruan'), ('thiago', 'Thiago')], default=1, max_length=30, verbose_name='Colaborador'),
            preserve_default=False,
        ),
    ]
