# Generated by Django 5.0 on 2024-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefa_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='colaborador',
            field=models.CharField(choices=[('RUAN', 'RUAN'), ('THIAGO', 'THIAGO')], max_length=30, verbose_name='Colaborador'),
        ),
    ]
