# Generated by Django 5.0.1 on 2024-02-24 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0005_delete_detalhescomputador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Computador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_computador", models.CharField(max_length=50)),
                ("numero_anydesk", models.CharField(max_length=20)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
