# Generated by Django 5.0.1 on 2024-03-13 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detalhes", "0002_computador_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="computador",
            name="data_manutencao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="computador",
            name="obs",
            field=models.CharField(
                default="Nenhuma observação.",
                max_length=100,
                verbose_name="Observações",
            ),
        ),
    ]
