# Generated by Django 5.0.1 on 2024-03-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detalhes", "0004_alter_computador_obs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computador",
            name="obs",
            field=models.TextField(),
        ),
    ]
