# Generated by Django 5.0.1 on 2024-02-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_detalhescomputador"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalhescomputador",
            old_name="empresa",
            new_name="empresa_id",
        ),
    ]
