# Generated by Django 5.0.1 on 2024-02-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_rename_empresa_id_detalhescomputador_empresa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DetalhesComputador",
        ),
    ]
