# Generated by Django 5.0 on 2024-01-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sistema', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('administrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_aniversario', models.DateField()),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_realizacao', models.DateField(auto_now_add=True)),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membro')),
            ],
        ),
    ]
